// Generate src/feeds.ts from a stocktensor-subnet assets.json.
// Usage: node scripts/gen-feeds.mjs [path/to/assets.json]
// Default source is the vendored copy in scripts/assets.json; refresh it with
// `cp ../stocktensor-subnet/stocktensor/assets.json scripts/assets.json`.
import { readFileSync, writeFileSync } from "node:fs";
import { getAddress } from "viem";

const source = process.argv[2] ?? new URL("./assets.json", import.meta.url);
const data = JSON.parse(readFileSync(source, "utf8"));
if (data.chain_id !== 4663) throw new Error("assets.json is not for Robinhood Chain (4663)");

const rows = data.assets
  .map((a) => ({ symbol: a.symbol, feed: getAddress(a.feed), decimals: a.decimals, name: a.name }))
  .sort((a, b) => a.symbol.localeCompare(b.symbol));

const body = `// Generated by scripts/gen-feeds.mjs from Chainlink's feed registry
// (${data.source}). Do not edit by hand.

export interface StockFeed {
  /** Stock token symbol, e.g. "NVDA". */
  readonly symbol: string;
  /** Chainlink proxy address on Robinhood Chain (4663). */
  readonly feed: \`0x\${string}\`;
  readonly decimals: number;
  /** Feed name in the Chainlink registry. */
  readonly name: string;
}

export const FEEDS: readonly StockFeed[] = ${JSON.stringify(rows, null, 2)} as const;
`;
writeFileSync(new URL("../src/feeds.ts", import.meta.url), body);
console.log(`wrote ${rows.length} feeds`);
